### ISSUE TITLE
Fail to create FTS index using RBAC

### ISSUE THREAD

**Issue by JesusTheHun** [differentway/couchmove#14]
Using `Couchmove 2.x` and RBAC, I get the following error for a FTS change :

```
Caused by: com.github.couchmove.exception.CouchmoveException: Could not store FTS index : {"error":"rest_auth: cbauth.AuthWebCreds, err: Authentication failure", ... }
```

This does not happen when I used the legacy way to authenticate.
Other type of changes work fine.

Edit : this happens inside of a k8s cluster
Edit 2 : just to be clear, I have upgraded the user to a full admin to be it was not a silly right mistake

**Comment by tchlyah** [comment]
What do you mean by legacy way to authenticate ? In my knowledge, beginning from Couchbase 5.0 you need to create an RBAC user with the correct rights in order to access your application.

I'm using RBAC and I don't have any issues! I'll need more details about that to be able to reproduce.

Did you try override the SDK version to the latest ([2.7.21](https://docs.couchbase.com/java-sdk/2.7/sdk-release-notes.html#version-2-7-21-14th-september-2021)) to see if it works ?
